package:
  name: sirius-csifingerid
  version: 4.0.1

build:
  number: 0

source:
  fn: sirius-4.0.1-linux64-headless.zip # [linux]
  url: https://bio.informatik.uni-jena.de/repository/dist-release-local/de/unijena/bioinf/ms/sirius/4.0.1/sirius-4.0.1-linux64-headless.zip # [linux]
  
requirements:
  build:
    - {{ compiler('c') }} 
    - patchelf
    - libgcc 
    - glpk
    - openjdk >=7
    
  run:
    - {{ compiler('c') }} 
    - patchelf
    - libgcc
    - glpk
    - openjdk >=7
    

test:
  commands:
    - sirius --version

about:
    home: https://bio.informatik.uni-jena.de/software/sirius/
    license: GPLv3
    summary: SIRIUS is new java-based software framework for discovering a landscape of de-novo identification of metabolites using single and tandem mass spectrometry. SIRIUS uses isotope pattern analysis for detecting the molecular formula and further analyses the fragmentation pattern of a compound using fragmentation trees.



