owner: tomnl
remote_repository_url: https://github.com/computational-metabolomics/sirius_csifingerid_galaxy
homepage_url:  https://github.com/computational-metabolomics/sirius_csifingerid_galaxy
categories: ["Metabolomics"]
description: "[Metabolomics][LC-MS][MS/MS] sirius csifingerid galaxy"
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "[Metabolomics][LC-MS][MS/MS] {{ tool_name }} {{description}}"
long_description: "[Metabolomics][LC-MS][MS/MS] sirius csifingerid galaxy"
